### ISSUE TITLE
View editor will not allow dot or forward slash in XMP property name

### ISSUE THREAD

**Issue by MetadataDeluxe** [adobe-dmeservices/custom-metadata#10]
**Description**
When editing the XMP property name, if I input a dot (".") or forward slash ("/") the save button is disabled and the error message "Property name cannot contain space character" appears. Both of these characters should be allowed. If I create a JSON file using them, the custom panel accepts them and reads/writes the expected XMP properties.

"." might be used rather than camel case in some schemas. I have not found a restriction on using "." in property names in the XMP spec.
Example:
work.agent

"/" is used to create an XMP structure. 
Example:
XMP Property Name: custom1/vrae:_label
XMP Property Name: custom1/vrae:data

<vrae:custom1 rdf:parseType="Resource">
	<vrae:_label>My Custom Field</vrae:_label>
	<vrae:data>My custom data</vrae:data>
</vrae:custom1>

**Steps to reproduce**
Open the view editor, enter an alphanumeric name containing either "." or "/" and no spaces.

**Workarounds**
Import a JSON file.

**Expected behavior**
Save button should be enabled and no error message should appear.
Error message "Property name cannot contain space character" should only appear if the name contains a space.

**Metadata View JSON**
[custom_panel_vra.zip](https://github.com/adobe-dmeservices/custom-metadata/files/5580865/custom_panel_vra.zip)

**Environment**
* OS type and version: Windows 10
* Extension version: 1.2.0

**Comment by jameslockman** [comment]
We have closed this issue with the 1.3.0 release. We now support complex structure notation as requested.
