### ISSUE TITLE
Metadata crash format when saved

### ISSUE THREAD

**Issue by mrtngrsbch** [adobe-dmeservices/custom-metadata#12]
When I save the file, the JSON format is broken

In 'View Editor' I open 'core_properties_view.json' > save file > crash

original vs saved file [Brackets Editor]:

![image](https://user-images.githubusercontent.com/693328/104850137-14c59d80-58cc-11eb-98d5-2e55223f1bd8.png)

original file:
JSON: [core_properties_view.zip](https://github.com/adobe-dmeservices/custom-metadata/files/5826466/core_properties_view.zip)

saved file:
JSON: [core_properties_view[saved].json.zip](https://github.com/adobe-dmeservices/custom-metadata/files/5826460/core_properties_view.saved.json.zip)

Best, Martin
MacOS Catalina 10.15.7
Adobe Bridge 2020 10.0.2.131

**Comment by jameslockman** [comment]
Your saved JSON appears to be properly formatted, but minified as expected. When I open it in Sublime Text and reformat the JSON, it parses properly. Also, it imported just fine for me.

I noticed that you are using Catalina. We have seen issues with systems that were upgraded to Catalina, in that some extensions need to be explicitly trusted again. Have you tried uninstalling Bridge and reinstalling? This should force the OS to validate file access. Alternatively, you can give Bridge Full Disk Access in the Privacy panel.

**Comment by mrtngrsbch** [comment]
Hey... Thanks a lot James !
I use AtoM and Brackets and I didn't know that Sublime Text feature ;-)

Even so, I find no interest in minifying a small JSON
best

**Comment by mrtngrsbch** [comment]
FYI: "Visual Studio Core" also reformats the code
