### ISSUE TITLE
View Editor Prefix Doesn't Match XMP Output

### ISSUE THREAD

**Issue by popeo** [adobe-dmeservices/custom-metadata#13]
Wasn't sure if this was a bug or working as intended but I used the view editor to setup custom fields (FbID and TouchType) initially using the prefix field "fb". I then changed this to "Attrib" and ever since, the XMP output showed a prefix of fb_1_, something I never set myself. I did get the prefix to read "fb" for some time before we made a change but I'm wondering why this seems to be stuck? Any tips would be hugely appreciated.

<img width="985" alt="Prefix Error - View Editor" src="https://user-images.githubusercontent.com/3730173/105530410-c0e4fb00-5cb5-11eb-9763-686b7477f154.png">

This is the setup of the View Editor which then yields the following:

   fb_1_:FbID="764842784121952"
   fb_1_:TouchType="1"

**Comment by jameslockman** [comment]
The prefix is a shorthand used by the XMPLib to provide a quick way to get to a namespace. If you tag a document with a property with specific prefix, the XMPLib will always use that prefix when addressing the document. You can try to remove that tag completely from the document and then re-tag it, but the data will end up in the right place, as defined by the property and the namespace. This might have an impact on a DAM, however, if it is expecting a specific prefix, but if the DAM respects the XMP spec, it won't matter so long as the _image_ is consistent in using one prefix to represent one namespace.

**Comment by popeo** [comment]
Thanks @jameslockman. To be clear, does this mean an asset tagged for the first time would retain Attrib: as the prefix whereas an asset incorrectly tagged (e.g. fb_1_) would never be able to drop that? I just want to be clear if this is an issue with the .json file or an issue with the tags in the image.

**Comment by jameslockman** [comment]
The XMPLib will target the namespace, not the prefix. It uses the prefix to know which namespace to target, so while the form itself uses Attrib, the prefix is irrelevant so long as it is consistent in your document. If you look at the raw XMP (via FileInfo), what does it say for the definition of http://attribution.com/ads/1.0/ ?
