### ISSUE TITLE
reduce name to one word

### ISSUE THREAD

**Issue by cwest01** [adobe-dmeservices/custom-metadata#14]
Custom Metadata Panel is a very long name to appear in a workspace layout. It unnecessarily crowds out the names of other window names. Bet you didn’t think of that 😊 

The word panel is superfluous, and the word data isn’t that useful in the context of metadata. How about naming it something like “Custometa,” for example.  I think single word names are much preferable for extension names.

![2021-02-11_18-58-27](https://user-images.githubusercontent.com/78942283/107722038-55ca8b00-6c9b-11eb-903d-5928f710d636.jpg)

**Comment by jameslockman** [comment]
The name will be Custom Metadata going forward.
