### ISSUE TITLE
Bridge CC 2019 crashes with extension on Mac OS 11.3

### ISSUE THREAD

**Issue by AnkeAugustin** [adobe-dmeservices/custom-metadata#16]
We are using the extension (v1.3.0) on Mac OS X 10.14 and 10.15. 
Today we tested it on OS 11.3, which doesn't work in our case. 
When we try to open Bridge (after a successful installation with ExManCmd), Bridge crashed immediately. 
It only happens with Adobe Bridge CC 2019. It does work with Adobe Bridge 2021.
 
We tried installing it with different versions of ExManCmd: 

**Version A**
An older Version, 7.3.4.597, which we were using up until 11.3. 
Extensions can be installed on 10.14 and 10.15 with this and Bridge starts normally.
But we can't install any extensions on our Mac OS 11.3 Client (Error Code 403 = EXMAN_FAILED_NO_PRODUCT_SUPPORT_THIS_CEP)

**Version B**
Latest Version downloaded here: https://medium.com/adobetech/exmancmd-7-11-1-update-for-apple-silicon-ca8cf8f22538 
We can install all our extensions on 10.14, 10.15, and 11.3. 
While the custom-metadata extension works on 10.14 and 10.15, Bridge CC 2019 crashes shortely after the start on 11.3.
We don't have this problem with other extensions we are using. 
Crash Report: [LOG_BR_19.txt](https://github.com/adobe-dmeservices/custom-metadata/files/6452019/LOG_BR_19.txt)

**Steps to reproduce**
- use a 11.3 client
- install Adobe Bridge CC 2019 
- download latest ExManCmd Version
- install extension mit ExManCmd on the 11.3 Client
- start Bridge CC 2019 >> it "should" crash

**Comment by jameslockman** [comment]
You may need Rosetta 2 to use CEP on Apple Silicon. Have you enabled that?

Also, please open a bug against Bridge, as the bug is not with the Custom Metadata Panel.

**Comment by AnkeAugustin** [comment]
Hi James!
Sorry for the confusion: the report is with "Custom Metadata Panel" - we just renamed it in the Manifest.xml to "Metadata Ausland", wo our users understand the use of it ;)
We will try it with Rosetta 2 and I will let you know! 
Thank you :)

**Comment by jameslockman** [comment]
Oh, it is not a good idea to change anything in the manifest, as it could break the signing and cause CEP to not load the extension.

**Comment by AnkeAugustin** [comment]
Believe me, please: we have, of course, also tested the Custom Metadata Panel without changes and had the same problem. I just said to my colleague to send me a report and he only sent me the attached report, without considering which of the panels (the original panel or the renamed panel) was installed when he saved the report. 
As I said: same problem exists with Custom Metadata Panel and in the report it only has an different name, because it was the "wrong" crash report my colleague saved. Can you adapt or do I need to reinstall it and let it crash, so you can get the right report? 

Back to the problem: I checked and Rosetta 2 is installed on all our computers. 
Do you have any other ideas? :)
