### ISSUE TITLE
Custom Metadata Panel for Adobe Premiere Pro

### ISSUE THREAD

**Issue by thegitterhub** [adobe-dmeservices/custom-metadata#17]
The Custom Metadata Panel works with Bridge, Photoshop, and Illustrator which is great.

Requesting to add it to Premiere Pro as well to achieve the same consistent metadata experience.

**The use case:**
We use the same schema for both images and video so the Custom Metadata Panel is a perfect fit.
Our videographer embeds metadata to video clips and images using Premiere Pro before, during, and after editing.
The Premiere Pro metadata panel can be configured to some degree to match some (but not all) of our schema. Even after we configure it, the Premiere panel still forces us to display schema headings from all the standard schemas we incorporated into our own which confuses the user (see image Premiere-Bridge1.jpg). In contrast, the Custom Metadata Panel allows us to create headings, dividers and we can organize our fields so they appear in a way that makes sense to us.
![Premiere-Bridge1](https://user-images.githubusercontent.com/86679000/123859217-a147a380-d8e1-11eb-9067-aac3b6d69fc5.jpg)

It is also difficult to incorporate our custom namespace for our own fields with Premiere Pro. In the Custom Metadata Panel, it's easy. It would be beneficial if the Custom Metadata Panel could appear in Premiere so that we have the same metadata experience as we do in Bridge, Photoshop and Illustrator. Currently, our videographer is adding some metadata with Premiere and then has to go to Bridge and add the rest. They also have to adjust mentally because the metadata panels look different in either application.

**Considerations:**
Premiere is unique from Photoshop/Bridge/Illustrator in that it allows you to choose whether to embed/write metadata to the file or only keep the metadata within the Premiere project file itself for select fields (such as description). This is done with a small button with a link icon to turn this on or off for select fields. If the Custom Metadata Panel is added to Premiere, this same functionality described above should be considered to be added to the panel so it is consistent with Premiere. (see image Premiere-Bridge2.jpg)
![Premiere-Bridge2](https://user-images.githubusercontent.com/86679000/123860063-a9541300-d8e2-11eb-87b1-f82aad502316.jpg)

**Comment by jameslockman** [comment]
@thegitterhub we have released version 1.6.1, which includes support for Premiere Pro. Please update your Custom Metadata Panel and launch Premiere Pro to see the panel.

**Comment by thegitterhub** [comment]
This is excellent!
Thank you James and team.
