### ISSUE TITLE
Mis-typed namespace persists even though all metadata for that namespace is deleted

### ISSUE THREAD

**Issue by dtrout** [adobe-dmeservices/custom-metadata#19]
While using View Editor to add my own metadata, I mis-typed the namespace for one of the properties.  I'm using "print" as the prefix.  For example, "print:Paper" is one of the properties.  After adding a few more properties using "print" as the prefix (using the **correct** namespace) I saved the JSON.  In Bridge I added these properties to a few images, then checked the RAW XMP using the FileInfo tool.  I saw the two namespaces, the bad one had "print" associated, the other had "print_1_".

To clean this up, I removed all image file XMP entries with either "print" or "print_1_" as the prefix (using ExifTool), uninstalled the Custom Metadata Panel and started from scratch.  However now when I specify "print" as the prefix in the CMP View Editor, I am getting "print_1_" as the prefix in the metadata.  It seems there is some residual left over artifact somewhere that is referencing the mis-typed namespace and therefore inserting "print_1_" in the XMP when I add these properties.

Is this a bug?  If not, how do I clean this up?  Is there an internal cache of namespaces that I need to somehow reset?

Thanks for a great tool!

**Comment by dtrout** [comment]
After some further testing, it appears that deleting all Bridge caches and then restarting Bridge resolves this issue (not sure if it is one or both actions that resolved it).  For now, I'll close this issue.

**Comment by jameslockman** [comment]
Clearing the cache makes sense, as Bridge will "remember" the prior state of an asset if it has touched it. Bridge does some manipulation between the asset and the user interface, so sometimes a clearing of the cache is a good idea.

We are curious about how you use the tool. Would you be willing to share some details, such as:

1. How many people in your group use it?
2. How are you distributing the config file to end users? 
3. Do you use Enterprise deployment or do users get the extension from the Marketplace?

**Comment by dtrout** [comment]
Thanks for your comments.

 

RE How I use the tool:  I’m just an individual (retired) running a very small side business doing large format digital fine art printing for other artists and photographers.  I’ve been wanting to improve my process for ingesting and tracking image assets from clients into my printing workflow, especially regarding tracking of settings used for printing proofs and finals.  I had been prototyping a Python program and SQLite to do this myself, but then it occurred to me that Bridge and XMP might be all I need.  CMP really was the key since it made it very easy to add custom properties into the XMP of each file rather than having to track things external to the file.  I’m still experimenting, but Bridge/CMP looks very promising as a solution.

 

Dave
