### ISSUE TITLE
Cannot save value to langAlt property

### ISSUE THREAD

**Issue by MetadataDeluxe** [adobe-dmeservices/custom-metadata#2]
Tested on version 1.1.0

When a value is entered in a field mapped to a langAlt property such as dc:title, dc:description, dc:rights, xmpRights:UsageTerms, it is not saved. Instead, this error is returned:

> Set - C:\Users\Computer User\Pictures\DEMO\1.jpg:http://purl.org/dc/elements/1.1/:description - XMP Exception: Composite nodes can't have values

**Comment by jameslockman** [comment]
This is a larger issue with language support in general. While many fields in various specs support localized values, there is no interface to provide access to those values. We are considering UI treatments so that users can add a French, German, Japanese, Klingon, etc. value for a specific property. We are concerned about the screen real estate and are working through some scenarios. This may not make it into the next release, but we do have it on the list of items we want to have in there.

**Comment by MetadataDeluxe** [comment]
It is very typical for apps to set the language default (implies the system language setting)
This is how the default Bridge panel does it:
```       
 <dc:description>
       <rdf:Alt>
           <rdf:li xml:lang="x-default">DESCRIPTION</rdf:li>
       </rdf:Alt>
</dc:description>
```

Adding options to set a specific language would be great, but might be more advanced than is necessary.

**Comment by MetadataDeluxe** [comment]
When editing an existing langAlt value, you could get the existing language value and use it to write the new value.

XMPMetaObj.getQualifier(schemaNS, structName, qualNS, qualName)

**Comment by jameslockman** [comment]
Yes, we agree. Also, know that Bridge doesn't have good support for managing the langAlt values. Consider "Desccription," that only allows the user to edit the default value and won't show any lang alts. We plan to show all alternative values for editing/reading.

**Comment by MetadataDeluxe** [comment]
True, none of the default metadata panels show, or allow edits to, alt language. Adding this as a feature to your panel would be great. Yes, it adds complexity and requires some knowledge of XMP principles, but your UI design is excellent and will open custom metadata editing to many more users.

**Comment by jameslockman** [comment]
This is scoped and is in our priority list for work to start after the release next week.

**Comment by jameslockman** [comment]
With the 1.3.0 release, alt-lang support is our highest priority.

**Comment by jameslockman** [comment]
@MetadataDeluxe Good news: we've added support for Language Alternatives in the 1.4.0 release!

If you have acquired [Custom Metadata Panel from Exchange](https://exchange.adobe.com/creativecloud.details.103752.html), then it will automatically update. If you have received it via your Enterprise Administrator as part of your Creative Cloud Desktop app, then it should also automatically update.

**Comment by MetadataDeluxe** [comment]
Great news, thanks!
