### ISSUE TITLE
Embedding Metadata for Video Files Intermittent

### ISSUE THREAD

**Issue by thegitterhub** [adobe-dmeservices/custom-metadata#20]
**DESCRIPTION:**
When trying to embedd metadata with the Custom Metadata Panel for video files, it says "Metadata Updated", but doesn't embed. However, on a second try, it embedds successfully.
It always works on the second try, never the first, unless embedding has never been attempted on a brand new video, in that case the first try works...but after that, you have to attempt two times. No error messages are displayed to indicate it's not working, but a manual check reveals that there's an issue. I can see when it works or not via the legacy metadata panel as well as the raw metadata in FileInfo.

When the first try works on a new video file for embedding **multiple** fields at one time, only every **second** field will embed, which is strange.

**NOTE:** .jpg files work fine, no issue, using the same testing method to embed.

**NOTE:** The legacy metadata panel does not have the issue when embedding the same fields for videos.

I've attached two screencast videos (no audio) demonstrating the issue, as well as the JSON file I'm using.

TESTING A SINGLE FIELD
https://user-images.githubusercontent.com/86679000/130837603-61fce7ce-da8b-4b10-bf33-93748648bf76.mp4

TESTING MULTIPLE FIELDS IN BATCH
https://user-images.githubusercontent.com/86679000/130837624-1689d5e6-272c-49c0-9d18-2cc8d36fd007.mp4

JSON FILE
[adobe_bridge_cmp_view.zip](https://github.com/adobe-dmeservices/custom-metadata/files/7048803/adobe_bridge_cmp_view.zip)

**HOW LONG HAS THIS ISSUE BEEN HAPPENING:**
I noticed something like this was happening from the first time I ever used the panel months ago...but we were only using images so it didn't have the problem. But we're doing more videos now and it's unavoidable. Only recently I have been able to replicate and explain the issue.

**WHAT HAVE I TRIED:**
1. Clearing Bridge Preferences
2. Uninstalling and Re-installing the Custom Metadata Panel using the Creative Cloud App Marketplace
3. Restarting my computer
4. Tried a fresh, blank .json file...and only added one field (dc:title)..still has issue.
5. Tried pointing the panel to the json file on my local hard drive as well as over a network share.
6. Tried various video codec/wrapers. h264.mp4, ProRes422Proxy.mov. Also tried a fresh premiere sequence with no imported video with only a title screen created in premiere exported to h264.mp4 (default Match Source - High Bitrate) and also ProRes422Proxy.mov. The issue still persisted in all cases. I did this incase there was something wrong with our videos but it doesn't seem to matter.
7. Sometimes the first try to embedd with the panel on a fresh video exported from premiere works...but only on every second field. Then after that, the first try/second try rule applies again.
8. Using the old legacy metadata panel in bridge does not have any issues for the same fields.
9. Tested on .jpg files, and there is no issue whatsoever.
10. Another user other than myself is also having these issues. We only have two users to test this at the moment.

This issue seems to affect all fields, including our custom namespace. But I can confirm it happends forsure on some standard ones such as: 
dc:creator
dc:contributor
dc:title
dc:description
dc:subject (keywords)
dc:rights

**SYSTEM SPECS:**
Computer: Lenovo ThinkPad P15v Gen1 (Laptop)
CPU: Core i7vPRO 10th GEN
GPU: NVIDIA Quadro P620
RAM: 32GB
Operating System: Windows 10 Enterprise Version 10.0.18363 Build 18363
Adobe Premiere Pro 15.1.0
Adobe Bridge 11.0.2.123
CustomMetadataPanel Version: I'm assuming it's the latest as I just uninstalled/reinstalled using the Creative Cloud App Marketplace.

**Comment by jameslockman** [comment]
We've developed a workaround that's been implemented in the [1.4.0 release](https://github.com/adobe-dmeservices/custom-metadata/releases).
For context, the Illustrator team pushed a release that did not include the XMP scripting framework on Mac. They plan to fix the issue in the October release, but if the Custom Metadata Panel is critical to Illustrator workflows, then please revert to an earlier version of Illustrator until October.
