### ISSUE TITLE
Multiple Value Actions Not Succeeding

### ISSUE THREAD

**Issue by thegitterhub** [adobe-dmeservices/custom-metadata#24]
**Description**
When two or more media files of any type (video, jpg, .ai, .tiff etc) are selected...cannot copy values from one file to the others using the multiple metadata values feature.
I have not attempted to replicate this issue on other user's systems at this time.

**Steps to reproduce**
1. Assured one file has metadata, and the other does not.
2. Select both in Bridge.
3. To the right of a metadata field, click on the icon to be able to copy metadata from one image to both for that field.
4. I can choose the menu items, but it has no effect when choosing a specific file. However, the "Merge All" option does seem to work.

**Workarounds**
No

**Expected behavior**
This used to work fine in the custom metadata panel in previous versions.

**Screenshots**
I've attached a screencast video named CopyMetadataIssue2.mp4 (no audio)

**XMP Metadata**
I've attached the two images I've tested in the screen cast video, you can get the RAW metadata from those.

**Metadata View JSON**
I've attached the json file named -->Learning_Central_(Basic_Embed).zip (json inside)<--

**Environment**
* OS type and version:
Windows 10 Enterprise version: 20H2 OS Build:19042.1766
* Extension version: 
Custom Panel Version 1.5.0
Bridge Version: 12.02.252
* Any other relevant info:
* 

![NZP-20181114-8734SB_BLACK AND WHITE](https://user-images.githubusercontent.com/86679000/181115859-429e67d5-6784-4cdc-8e3d-d1d307914736.jpg)
![NZP-20181114-8734SB](https://user-images.githubusercontent.com/86679000/181115878-e97c42cb-8931-40a3-aaf8-49e31b7d2b36.jpg)
[Learning_Central_(Basic_Embed).zip](https://github.com/adobe-dmeservices/custom-metadata/files/9193470/Learning_Central_.Basic_Embed.zip)

https://user-images.githubusercontent.com/86679000/181116066-0d7d4f39-95cf-4453-b3bc-542524079644.mp4

**Comment by bhunut-adobe** [comment]
@thegitterhub I was able to replicate the issue. Look like in this release, the Conflict Menu is broken completely.  We were able to identify the issue and will release a fix for this shortly.

**Comment by thegitterhub** [comment]
That’s awesome, thanks for looking into it so quickly.

From: Kevin Bhunut ***@***.***>
Sent: Wednesday, July 27, 2022 3:47 PM
To: adobe-dmeservices/custom-metadata ***@***.***>
Cc: Tony Welter ***@***.***>; Mention ***@***.***>
Subject: EXTERNAL EMAIL: Re: [adobe-dmeservices/custom-metadata] Multiple Value Actions Not Succeeding (Issue #24)

EXTERNAL EMAIL: Take extra caution when clicking links or opening files. Report any suspected phishing.

@thegitterhub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthegitterhub&data=05%7C01%7Ctwelter%40saskpower.com%7Ce2e81f752e414976a25108da70198559%7Cdbe9bd7b4b3a44b3b358e61ff34d58b2%7C0%7C0%7C637945552153055187%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nNrjJdC82zwlsJEnVDLSJk1c0y8hYWJa52c4GBGYTWw%3D&reserved=0> I was able to replicate the issue. Look like in this release, the Conflict Menu is broken completely. We were able to identify the issue and will release a fix for this shortly.

—
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadobe-dmeservices%2Fcustom-metadata%2Fissues%2F24%23issuecomment-1197403396&data=05%7C01%7Ctwelter%40saskpower.com%7Ce2e81f752e414976a25108da70198559%7Cdbe9bd7b4b3a44b3b358e61ff34d58b2%7C0%7C0%7C637945552153055187%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3b84OqJhc929jzaqxkq3jTVx%2FUqHebGWtmJmZou%2FLzA%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUVJ3WDOMDNS5CQ32Z6HGN3VWGU43ANCNFSM54XM464Q&data=05%7C01%7Ctwelter%40saskpower.com%7Ce2e81f752e414976a25108da70198559%7Cdbe9bd7b4b3a44b3b358e61ff34d58b2%7C0%7C0%7C637945552153055187%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SaNT5HyHPmlLM8Gbw8ahWMNkoisSRp7h3h8Pvgv7UQk%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

This email including attachments is confidential and proprietary. If you are not the intended recipient, any redistribution or copying of this message is prohibited. If you have received this email in error, please notify us by return email, and delete this email.

**Comment by bhunut-adobe** [comment]
@thegitterhub I have released the updated zxp. You can download and install it.  The one in Adobe Exchange hasn't been update yet.

https://github.com/adobe-dmeservices/custom-metadata/releases/tag/1.5.1

If you are not familiar with ZXP, you can use either of these tools to install it.
https://install.anastasiy.com/
https://zxpinstaller.com/

**Comment by MKelly-Adobe** [comment]
This bug has been resolved.

**Comment by jameslockman** [comment]
1.5.1 has been submitted to Marketplace for review. We have also replaced the version in the bug fix release here to include some cosmetic changes for this release.

**Comment by thegitterhub** [comment]
works good now. just updated from the marketplace. thanks again.
