### ISSUE TITLE
Numerical Field

### ISSUE THREAD

**Issue by BassaK** [adobe-dmeservices/custom-metadata#25]
Hi There

We are looking for a Metadata editor to fit into our new DAM solution and the Adobe Bridge Custom Metadata Panel, seems to be the right tool, however one very important feature it is missing is a Numerical Value Field.

**Therefore I am raising a Feature Request.**

There is currently a TEXT field, but a NUMERICAL value field is what I require to define a page number or issue number.  
FYI: An Issue number is a 4 digit number made up of  a 2 digit week or month number, and an abbreviated 2 digit year code (eg 0622, represents June 2022).  So basically the NUMERICAL field is to accept Numerals ONLY.

Secondly if you were to implement a NUMERICAL field, it would also be nice to have an option to define how many digits are allowed or restricted to being entered.  For example Maximum number allowed to be entered is 999 (therefore only accept 3 digits).

Also another request (option / preference) is that all numbers input must be defined as a 3 digit number, therefore for example 5 would have to be entered with 2 trailing zeros, so it would be entered as 005, and 26 would be entered as 026.

**Comment by AdobeAtlien** [comment]
Thank you for your feature request. The development team will research options make every attempt to satisfy your need.

Reggie R. Walker
Senior Manager - TSS Developers
________________________________
From: BassaK ***@***.***>
Sent: Wednesday, September 14, 2022 12:23:58 AM
To: adobe-dmeservices/custom-metadata ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [adobe-dmeservices/custom-metadata] Numerical Field (Issue #25)


EXTERNAL: Use caution when clicking on links or opening attachments.


Hi There

We are looking for a Metadata editor to fit into our new DAM solution and the Adobe Bridge Custom Metadata Panel, seems to be the right tool, however one very important feature it is missing is a Numerical Value Field.

Therefore I am raising a Feature Request.

There is currently a TEXT field, but a NUMERICAL value field is what I require to define a page number or issue number.
FYI: An Issue number is a 4 digit number made up of a 2 digit week or month number, and an abbreviated 2 digit year code (eg 0622, represents June 2022). So basically the NUMERICAL field is to accept Numerals ONLY.

Secondly if you were to implement a NUMERICAL field, it would also be nice to have an option to define how many digits are allowed or restricted to being entered. For example Maximum number allowed to be entered is 999 (therefore only accept 3 digits).

Also another request (option / preference) is that all numbers input must be defined as a 3 digit number, therefore for example 5 would have to be entered with 2 trailing zeros, so it would be entered as 005, and 26 would be entered as 026.

**Comment by jameslockman** [comment]
This is supported as of version 2.0.0.
You can achieve the leading zeroes by defining a maximum value (such as 999) and enabling leading zeroes.
