### ISSUE TITLE
It seems CEPHtmlEngine hangs up c/o Bridge custom metadata panel extension. 

### ISSUE THREAD

**Issue by ny-native2017** [adobe-dmeservices/custom-metadata#26]
Spinning wheel window trying to “Open View Editor” "default"

Mac OS 10.14.6 / Bridge 2021 / just downloaded ext. today

I’ve installed the custom metadata panel extension for Bridge and when I press the Settings button in that panel I'm given two choices one of which is the “Open View Editor” and below it I select default and then a new window opens with a spinning circle and just gets stuck permanently. I later got a system message that this process is stuck…

High CPU usage due to CEPHtmlEngine 

Thanks in advance for any help.

Paul

High CPU usage due to CEPHtmlEngine (Bridge Custom Metadata Panel 

cwd
/
txt
/Applications/Adobe Bridge 2021/Adobe Bridge 2021.app/Contents/MacOS/CEPHtmlEngine.app/Contents/Frameworks/CEPHtmlEngine Helper.app/Contents/MacOS/CEPHtmlEngine Helper
txt
/Library/Preferences/Logging/.plist-cache.WDeGDZEL
txt
/Applications/Adobe Bridge 2021/Adobe Bridge 2021.app/Contents/MacOS/CEPHtmlEngine.app/Contents/Frameworks/Chromium Embedded Framework.framework/Resources/en.lproj/locale.pak
txt
/Applications/Adobe Bridge 2021/Adobe Bridge 2021.app/Contents/MacOS/CEPHtmlEngine.app/Contents/Frameworks/Chromium Embedded Framework.framework/Resources/cef_100_percent.pak
txt
/usr/share/icu/icudt62l.dat
txt
/Applications/Adobe Bridge 2021/Adobe Bridge 2021.app/Contents/MacOS/CEPHtmlEngine.app/Contents/Frameworks/Chromium Embedded Framework.framework/Resources/icudtl.dat
txt
/Applications/Adobe Bridge 2021/Adobe Bridge 2021.app/Contents/MacOS/CEPHtmlEngine.app/Contents/Frameworks/Chromium Embedded Framework.framework/Resources/cef.pak
txt
/Applications/Adobe Bridge 2021/Adobe Bridge 2021.app/Contents/MacOS/CEPHtmlEngine.app/Contents/Frameworks/Chromium Embedded Framework.framework/Resources/cef_200_percent.pak
txt
/Applications/Adobe Bridge 2021/Adobe Bridge 2021.app/Contents/MacOS/CEPHtmlEngine.app/Contents/Frameworks/Chromium Embedded Framework.framework/Resources/cef_extensions.pak
txt
/Applications/Adobe Bridge 2021/Adobe Bridge 2021.app/Contents/MacOS/CEPHtmlEngine.app/Contents/Frameworks/Chromium Embedded Framework.framework/Resources/devtools_resources.pak
txt
/Library/Application Support/CrashReporter/SubmitDiagInfo.domains
txt
/System/Library/Extensions/AppleIntelKBLGraphicsVAME.bundle/Contents/MacOS/AppleIntelKBLGraphicsVAME
txt
/System/Library/Extensions/AppleIntelKBLGraphicsVADriver.bundle/Contents/MacOS/AppleIntelKBLGraphicsVADriver
txt
/usr/lib/dyld
txt
/Applications/Adobe Bridge 2021/Adobe Bridge 2021.app/Contents/MacOS/CEPHtmlEngine.app/Contents/Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework
0
/dev/null
1
/Users/paul/Library/Logs/CSXS/CEPHtmlEngine10-KBRG-11.1.1.185-com.adobe.custom-metadata-cep.configurator.log
2
/Users/paul/Library/Logs/CSXS/CEPHtmlEngine10-KBRG-11.1.1.185-com.adobe.custom-metadata-cep.configurator.log
3
/Users/paul/Library/Logs/CSXS/CEPHtmlEngine10-KBRG-11.1.1.185-com.adobe.custom-metadata-cep.configurator.log
4
/Applications/Adobe Bridge 2021/Adobe Bridge 2021.app/Contents/MacOS/CEPHtmlEngine.app/Contents/Frameworks/Chromium Embedded Framework.framework/Resources/icudtl.dat
5
->0xdf975f385c61fe43
6
/Applications/Adobe Bridge 2021/Adobe Bridge 2021.app/Contents/MacOS/CEPHtmlEngine.app/Contents/Frameworks/Chromium Embedded Framework.framework/Resources/en.lproj/locale.pak
7
/Applications/Adobe Bridge 2021/Adobe Bridge 2021.app/Contents/MacOS/CEPHtmlEngine.app/Contents/Frameworks/Chromium Embedded Framework.framework/Resources/cef.pak
8
/Applications/Adobe Bridge 2021/Adobe Bridge 2021.app/Contents/MacOS/CEPHtmlEngine.app/Contents/Frameworks/Chromium Embedded Framework.framework/Resources/cef_100_percent.pak
9
/Applications/Adobe Bridge 2021/Adobe Bridge 2021.app/Contents/MacOS/CEPHtmlEngine.app/Contents/Frameworks/Chromium Embedded Framework.framework/Resources/cef_200_percent.pak
10
/Applications/Adobe Bridge 2021/Adobe Bridge 2021.app/Contents/MacOS/CEPHtmlEngine.app/Contents/Frameworks/Chromium Embedded Framework.framework/Resources/cef_extensions.pak
11
/Applications/Adobe Bridge 2021/Adobe Bridge 2021.app/Contents/MacOS/CEPHtmlEngine.app/Contents/Frameworks/Chromium Embedded Framework.framework/Resources/devtools_resources.pak
12
/dev/urandom
13
/Library/Application Support/CrashReporter/SubmitDiagInfo.domains
14
count=0, state=0x12
15
count=0, state=0x12
16
->0xdf975f385c61ff0b

**Comment by bnickila-adobe** [comment]
Hey @ny-native2017 , thank you for reporting this issue. The default configuration json gets created in macOS: /Library/Application Support/Adobe/CEP/extensions on a Mac. Is it possible that you don't have admin access to that location? Are you able to create a new configuration under "Open tab management"? 

Either way, we'll look into, and hopefully resolve, the issue you're having. Thanks again!

**Comment by ny-native2017** [comment]
Hi Brian,

Thanks for replying. I should have admin access across the board. I was able to open tab management, so let me see if I can get to where I need to be that way.

I don’t have CEP, only this… CEPServiceManager4 - it contains 4 folders, nothing that seems rated to this extension.

Best,

Paul

**Comment by ny-native2017** [comment]
Besides the tech glitch I wrote about earlier I should mention another anomaly. When I go to CMP settings I see the attached screen, nothing about JSON or a slot to plug-in a URL. I should also mention my goal which is this… since I work in a video environment the fact that Dublin Core is built into Adobe Premiere makes that schema more attractive than Bridge’s default IPTC. So I'd like to use the custom metadata panel to short list a handful of useful fields from Dublin Core.

In the YouTube overview video there is no mention of Tab Management, nor do I see it mentioned in the GitHub manual. However there is lots about the View Editor that I am not able to open. Please advise.

Thanks and advance for any help

Paul

![Bridge Custom Metadata Panel - Settings (no URL slot or JSON prompt](https://user-images.githubusercontent.com/33795379/211650093-96b9d084-185d-4788-a62d-fcc5ecfbcbeb.png)

**Comment by bnickila-adobe** [comment]
Thanks for the insight. Soon, we'll be introducing the functionality of the panel in Premiere Pro. Hopefully we have these kinks worked out by then. 

In the meantime, from the screenshot you provided, you can click on Open Tab Management..." and click Create New like in my screenshot below. You can then choose "Load Example Data" where you'll see an option for Dublin Core. You can do this, or you can create one from scratch.

Please let me know if you run into any issues with this.

![MicrosoftTeams-image (14)](https://user-images.githubusercontent.com/91214672/211675419-c2a31473-a76a-4d24-874b-829439ca8aa7.png)
![MicrosoftTeams-image (15)](https://user-images.githubusercontent.com/91214672/211675470-1d525ad8-14c8-4569-bb52-3cb46f631e79.png)

**Comment by ny-native2017** [comment]
Thanks Brian, when I select "Create New" as instructed I get a big grey window with a spinning blue circle that is stuck just was it was with “Open View Editor” If I can get past this jam I think I might be off and running with what you suggested

**Comment by jameslockman** [comment]
We've made some adjustments that you can view in the [2.0.2 beta 1 release](https://github.com/adobe-dmeservices/custom-metadata/releases/tag/2.0.2). Please download and see if this works for you!

**Comment by jameslockman** [comment]
Closed in https://github.com/adobe-dmeservices/custom-metadata/releases/tag/2.0.2
