### ISSUE TITLE
Can the multiline text field box height be customized?

### ISSUE THREAD

**Issue by UXPublishing** [adobe-dmeservices/custom-metadata#27]
I just installed the Custom Metadata extension for Adobe Bridge. 

Is there a way to customize the height of the multiline text box for multiline text fields like Description, which often contains very long paragraphs. Right now, every time Bridge starts, I have to expand the box height by using the cursor.

Also, is there a way to customize the font-size of the panel labels and metadata fields?

**Comment by jameslockman** [comment]
Good evening! 
This is a great suggestion. How would you expect the option to work? Should Multiline text boxes automatically grow to show the entire text, or are you asking for an additional parameter that sets the initial size of the box?

When you ask to customize the font size, are you asking on a per item basis or are you asking to increase or decrease the font size for the entire UI? We recognize that the panel does not honor the UI scaling setting right now, but we should make it consistent with the UI settings. 
![image](https://github.com/adobe-dmeservices/custom-metadata/assets/2659225/0205e104-ac7a-433c-b16f-63ae1bdeffff)

**Comment by UXPublishing** [comment]
Hi, James, 
If the multiline text field is not empty, then the text box should be sized to fit the content. I think the default metadata panel automatically changes the height of the Description field to fit the content.
If the multiline text field is empty, then it would be nice to be able to either auto-resize as you type. Otherwise, it would be ok to have a basic setting that defines the default box height for each field. For instance, a multiline Description would be taller than multiline Title.

With font sizes, I think it would be sufficient to set a common font size for all text in the custom metadata panel. 
Right now, if I use Windows 10 screen scaling or the Adobe Bridge scaling settings, the custom metadata panel fonts are a lot larger than all the other text in the default panels. 
![image](https://github.com/adobe-dmeservices/custom-metadata/assets/87587099/89a4dc9a-7ef5-46cc-b0f4-f7467599a8fd)

Thanks!

**Comment by jameslockman** [comment]
We've made some adjustments that you can view in the [2.0.2 beta 1 release](https://github.com/adobe-dmeservices/custom-metadata/releases/tag/2.0.2). Please download and see if this works for you!

**Comment by jameslockman** [comment]
Closed in https://github.com/adobe-dmeservices/custom-metadata/releases/tag/2.0.2
