### ISSUE TITLE
Panel is blank when Bridge opens

### ISSUE THREAD

**Issue by MetadataDeluxe** [adobe-dmeservices/custom-metadata#29]
**Description**
If the Custom Metadata Panel is not active when Bridge opens, when you select it, it does not load (the panel is blank). Closing then re-opening Custom Metadata Panel forces it to load.

**Steps to reproduce**
1. Select a thumbnail and use the native metadata panel to edit the metadata.
2. Close Bridge
3. Open Bridge (native metadata panel is active)
4. Select the Custom Metadata Panel (panel is blank)

**Workarounds**
- Be sure the Custom Metadata Panel is active before you close Bridge.
- If the panel is blank, close the panel then re-open it using the menu Window > Extensions

**Expected behavior**
The Custom Metadata Panel should load when selected

**Screenshots**
![image](https://github.com/adobe-dmeservices/custom-metadata/assets/5862936/1ed4247c-8627-4fb3-b720-b13c18b638b6)

**Environment**
Windows 10 Pro x64 21H1 / Intel i5-7200U
Bridge 13.0.3.693
Bridge prerelease 14.0.0.41

**Comment by jameslockman** [comment]
Thanks. We'll investigate.

**Comment by jameslockman** [comment]
Quick question: do you have the Startup Scripts enabled?
![Screenshot_8_4_23__3_03_PM](https://github.com/adobe-dmeservices/custom-metadata/assets/2659225/93b20ea6-9930-4e8c-a924-50724d2e8456)

**Comment by MetadataDeluxe** [comment]
I just re-ran my scenario and Startup Scripts is enabled. 
I only get the blank panel when Custom Metadata Panel is not active when Bridge opens. I have seen this on both the native metadata panel and keyword panel. For example, if the last action I did before closing Bridge was assign a keyword with the keyword panel, when I re-open Bridge, the keyword panel is active. If I select the Custom Metadata Panel, it is blank.

I wonder if the startup script is not being read in this scenario?

**Comment by jameslockman** [comment]
Got it. This may be harder to diagnose, because it may be platform dependent. We don't see this behavior on Mac, for instance. 
Have you tried to uninstall the extension from Creative Cloud Desktop, and then reinstall it? You might want to restart in between. If that doesn't solve it, we might send you a custom build with debugging enabled so we can get some additional details.

**Comment by MetadataDeluxe** [comment]
I'll try reinstalling.
I have a lot of other scripts loaded. I'll try disabling them.

This may not be related at all, but I use Extendscript Toolkit and when it opens, I get this alert about adobe-dmeservices/custom-metadata:
![image](https://github.com/adobe-dmeservices/custom-metadata/assets/5862936/ee09b7d2-526b-4827-be4e-05a56fbd6f92)

I've never opened any of the custom-metadata files in Extendscript, so I don't know why that alert would show. It's very possible Extendscript is the problem, but the blank Custom Metadata Panel happens when Extendscript Toolkit is running or not.

**Comment by MetadataDeluxe** [comment]
I disabled all other startup scripts and still had the blank panel problem.
I'm going to ask a colleague to attempt to replicate the problem. I'll report when I get their results.

**Comment by MetadataDeluxe** [comment]
A colleague was able to reproduce the problem using Bridge 13.0.3.693 on Windows 10. She also removed other startup scripts so only the Custom Metadata Panel was being used.

**Comment by jameslockman** [comment]
We are unable to replicate this one.
