### ISSUE TITLE
Add custom tooltips to display objects

### ISSUE THREAD

**Issue by MetadataDeluxe** [adobe-dmeservices/custom-metadata#30]
I would like to be able to add custom tooltips to the Display Name and input object (text box, dropdown, etc.)

**Comment by jameslockman** [comment]
Tell us more. Where would you see these appearing? there are two objects there: the display name and the input itself. We already include text that displays when the user has not input anything in some fields. Would you want to see different tooltips for the display name and the input?

**Comment by MetadataDeluxe** [comment]
Yes, I was thinking of separate tooltips for the display name and the input.
Display name tooltip might be the property definition.
Input tooltip might be example values.

I was trying to recreate this JavaScript panel:
Hover over "Creator"
![image](https://github.com/adobe-dmeservices/custom-metadata/assets/5862936/7df218ad-90c3-446a-8ad3-a5c297740e99)

Hover over Creator input:
![image](https://github.com/adobe-dmeservices/custom-metadata/assets/5862936/0fb93c17-c22e-4b01-ae3c-bb7223adc2f6)

**Comment by MetadataDeluxe** [comment]
Something like this:

![image](https://github.com/adobe-dmeservices/custom-metadata/assets/5862936/e4d7261b-181c-4f73-92b8-0d9b7be4b016)

![image](https://github.com/adobe-dmeservices/custom-metadata/assets/5862936/56e0421a-a34c-4a2a-b750-b68292b33095)

**Comment by jameslockman** [comment]
Excellent. Looks like you've been studying our Spectrum UI kit :)

**Comment by jameslockman** [comment]
We are looking at this request more closely in the context of the Spectrum design language. We are planning to move to the open source React-Spectrum V3 kit, which will require some recoding on our part. This will likely happen at the same time, so please be patient.

**Comment by MetadataDeluxe** [comment]
Thanks, I appreciate that you are considering adding it.

**Comment by xoogu** [comment]
I would greatly appreciate this as well. For some metadata a lengthy description of what it means and possible values etc. can be quite useful and there's not really any way of doing this with the current implementation.

**Comment by jameslockman** [comment]
We've made some adjustments that you can view in the [2.0.2 beta 1 release](https://github.com/adobe-dmeservices/custom-metadata/releases/tag/2.0.2). Please download and see if this works for you!

**Comment by jameslockman** [comment]
Closed in https://github.com/adobe-dmeservices/custom-metadata/releases/tag/2.0.2
