### ISSUE TITLE
Error messages since the latest update of Adobe Bridge

### ISSUE THREAD

**Issue by mendes-bridge** [adobe-dmeservices/custom-metadata#33]
Hi,

Since the latest update of Adobe Bridge (version 14.02.191, 2024), my custom metadata panels no longer open and I am getting error messages. I have tried this on different computers and the problem persists (Operating system: Windows 10 and Windows 11).

Could you please help me with this issue?

**Comment by jameslockman** [comment]
Can you try something for us:

1. Quit Bridge
2. Uninstall the panel using Creative Cloud Desktop
![image](https://github.com/adobe-dmeservices/custom-metadata/assets/2659225/be409f87-303b-40bf-96c8-12515231a8f5)

3. Reinstall the panel using CC Desktop

**Comment by mendes-bridge** [comment]
Thank you very much! My problem seems to be solved. I've also deleted and reinstated my custom metadata panels.
Best regards
