### ISSUE TITLE
Number properties show an error

### ISSUE THREAD

**Issue by nitmws** [adobe-dmeservices/custom-metadata#34]
**Description**

Properties with a numeric value at the top level of property structure show an error (red frame) while such properties show no error if they are in a nested structure.

**Steps to reproduce**

* Set up of property with the data type Number, in the Advanced setup set "Allow decimal digits" to No or Yes, depending on the data type
* Example: XMP prefix = Iptc4xmpExt, XMP namespace = http://iptc.org/std/Iptc4xmpExt/2008-02-29/, XMP property name = MaxAvailWidth
* Read metadata from an image with the IPTC Max Available Width property, e.g. attached file.

**Workarounds**
None.

**Expected behavior**
Show the value without an error indicator.

**XMP Metadata**
Attached

**Metadata View JSON**
Attached

**Environment**
* OS type and version: Windows 11
* Extension version: latest
[IptcPmd20231_cupmdpnl03a.json](https://github.com/adobe-dmeservices/custom-metadata/files/14515733/IptcPmd20231_cupmdpnl03a.json)
[IPTC-PhotometadataRef-Std2023.1_XMP.zip](https://github.com/adobe-dmeservices/custom-metadata/files/14515750/IPTC-PhotometadataRef-Std2023.1_XMP.zip)

**Comment by jameslockman** [comment]
We've made some adjustments that you can view in the [2.0.2 beta 1 release](https://github.com/adobe-dmeservices/custom-metadata/releases/tag/2.0.2). Please download and see if this works for you!

**Comment by nitmws** [comment]
I confirm the numeric values of MaxAvailWidth and MaxAvailHeight are shown correctly in 2.0.2.b1
ThumbsUp.
