### ISSUE TITLE
Text properties in a nested structure show non-ASCII characters in a wrong way

### ISSUE THREAD

**Issue by nitmws** [adobe-dmeservices/custom-metadata#37]
**Description**
Text with non-ASCII characters in a property being the member of a structure show the literal values of UTF-8 bytes. (Note: such characters are shown correctly in properties which are not nested.)

**Steps to reproduce**
* Install the attached view JSON file
* Show the metadata of an image with non-ASCII characters in a nested property. E.g. the Sublocation of Location Shown of the attached image

**Workarounds**
None

**Expected behavior**
Show non-ASCII characters with UTF-8 encoding as the correct characters. E.g. "TÃ¼rkenschanzpark" should be "Türkenschanzpark"

**Screenshots**
Attached

**XMP Metadata**
attached

**Metadata View JSON**
attached

**Environment**
* OS type and version: Windows 11
* Extension version: latest
[IptcPmd20231_cupmdpnl03a.json](https://github.com/adobe-dmeservices/custom-metadata/files/14516007/IptcPmd20231_cupmdpnl03a.json)
![TextWithUmlaut-error](https://github.com/adobe-dmeservices/custom-metadata/assets/1301232/0e1b5dd2-7660-4385-bbd8-7c1f67a7fbf9)
![TextWithUmlaut-ok](https://github.com/adobe-dmeservices/custom-metadata/assets/1301232/94763206-f251-4913-a864-f5d2870297b4)
[IPTC-PhotometadataRef-Std2023.1_XMP.zip](https://github.com/adobe-dmeservices/custom-metadata/files/14516009/IPTC-PhotometadataRef-Std2023.1_XMP.zip)

**Comment by jameslockman** [comment]
Thank you for reporting. We've verified that this is happening during the XMP Read operation in Extendscript. We are investigating methods to ensure that the unicode characters do not get scrambled.

**Comment by jameslockman** [comment]
We have a solution and will release with a number of features soon.

**Comment by jameslockman** [comment]
We've made some adjustments that you can view in the [2.0.2 beta 1 release](https://github.com/adobe-dmeservices/custom-metadata/releases/tag/2.0.2). Please download and see if this works for you!

**Comment by nitmws** [comment]
I tested with version 2.0.2b1 the image used above and confirm the sublocation is shown correctly as "Türkenschanzpark".
ThumbsUp.
