### ISSUE TITLE
Presets don't work with Alt-lang fields

### ISSUE THREAD

**Issue by xoogu** [adobe-dmeservices/custom-metadata#43]
Create a view with an Alt-Lang text field:
`[
  {
    "id": "BOUPjT3cFO",
    "displayName": "Copyright notice",
    "prefix": "dc",
    "namespace": "http://purl.org/dc/elements/1.1/",
    "propertyName": "rights",
    "type": "Text",
    "dependencies": [],
    "readOnly": false,
    "altLangEnabled": true,
    "disabled": false
  }
]`

Fill in a value and save it as a preset. Now delete your value and apply the preset you just saved and you'll get an error "Cannot apply preset: Field object not found for x-default"

If we look at the saved preset, that is:
`  {
    "name": "Test",
    "presets": {
      "x-default": "Test"
    }
  }`

If we change this to replace "x-default" with the id of our field "BOUPjT3cFO" we instead get the error "Cannot apply preset: Field object not found for BOUPjT3cFO".
I have also tried for the preset:
`  {
    "name": "Test",
    "presets": {
      "BOUPjT3cFO" : {
        "x-default": "Test"
      }
    }
  }`
and
`  {
    "name": "Test",
    "presets": {
      "BOUPjT3cFO" : [{
        "x-default": "Test"
      }]
    }
  }`
But same error.

**Comment by jameslockman** [comment]
Thanks for reporting. This will be fixed in the next release (code complete for this fix, awaiting other features to settle down).

**Comment by jameslockman** [comment]
We've made some adjustments that you can view in the [2.0.2 beta 1 release](https://github.com/adobe-dmeservices/custom-metadata/releases/tag/2.0.2). Please download and see if this works for you!

**Comment by jameslockman** [comment]
Closed in https://github.com/adobe-dmeservices/custom-metadata/releases/tag/2.0.2
