### ISSUE TITLE
Filtering list of options not working.

### ISSUE THREAD

**Issue by xoogu** [adobe-dmeservices/custom-metadata#45]
**Description**
Filtering list of options is not working. No options show in the dropdown list. I have it set so 'Lens Model' is dependent on and filtered based on the value of 'Lens Manufacturer'. But after selecting a Lens Manufacturer, there are no values to choose from in Lens Model.
![filtering-options-not-working](https://github.com/user-attachments/assets/ee2fa772-a593-48fc-b898-71803f52c918)

Note 'Lens' is dependent on Lens Manufacturer and Lens Model and filtered by Lens Model, and the value shown in this screenshot is being autofilled from the EXIF, not a manually entered value. I have tried with an image that has no EXIF Lens value and get the same results.

**XMP Metadata**
[DSCF4004.txt](https://github.com/user-attachments/files/18199612/DSCF4004.txt)

**Metadata View JSON**
[Camera,_lens,_etc.json](https://github.com/user-attachments/files/18199618/Camera._lens._etc.json)

Win 10, Bridge 15.0.1.412, Panel ver. 2.0.3

**Comment by jameslockman** [comment]
Thank you for reporting. We've identified the issue and have a solution. We are trying to get it into production before Adobe's holiday break, but there is no guarantee it will be available in Marketplace before Jan 3, 2025.

**Comment by jameslockman** [comment]
Can you please test this with [the latest beta release](https://github.com/adobe-dmeservices/custom-metadata/releases/tag/2.0.4beta1)? 
We also added a feature where you can set a filtered field to automatically choose the remaining option when the option list is reduced to a single value.

**Comment by xoogu** [comment]
Thanks! That fixes the issue. Not tried the auto-select yet, but should be a useful feature for me.
