### ISSUE TITLE
dc:creator saved as bag - should be seq

### ISSUE THREAD

**Issue by MetadataDeluxe** [adobe-dmeservices/custom-metadata#7]
**Description**
When a dc:creator property is created or edited, it is saved as a bag array, but according to the XMP spec, it should be saved as a seq array.

**Steps to reproduce**
1. use the View Editor to create a new field
2. set the XMP Prefix to "dc"
3. set the XMP Namespace to "http://purl.org/dc/elements/1.1/"
4. set the XMP Property to "creator"
5. Save
6. enter a value in the new field.
7. Save
8. view raw XMP:

         <dc:creator>
            <rdf:Bag>
               <rdf:li>CREATOR</rdf:li>
            </rdf:Bag>
         </dc:creator>

**Workarounds**
None

**Expected behavior**

         <dc:creator>
            <rdf:Seq>
               <rdf:li>CREATOR</rdf:li>
            </rdf:Seq>
         </dc:creator>

**XMP Metadata**
[custom_metadata_test_1_2_0.zip](https://github.com/adobe-dmeservices/custom-metadata/files/5528055/custom_metadata_test_1_2_0.zip)

**Metadata View JSON**
[reser_cmp_view.zip](https://github.com/adobe-dmeservices/custom-metadata/files/5528065/reser_cmp_view.zip)

**Environment**
* Windows 10.0.19041
* Extension version: 1.2.0

**Comment by jameslockman** [comment]
I've reviewed your JSON, and I noticed that you did not specify that Creator needed to be a seq. 

Open the View Editor, click the pencil, and switch to the Advanced tab. Change the Array Type to Seq. The default is Bag.

![Screenshot_11_12_20__8_43_AM](https://user-images.githubusercontent.com/2659225/98947641-7aa83a00-24c3-11eb-8e2f-84cee8dade2e.png)

**Comment by MetadataDeluxe** [comment]
That was my mistake, I missed the array type option. After changing that to Seq, dc:creator is working properly.

**Comment by jameslockman** [comment]
Super! Glad it works!
