### ISSUE TITLE
Installation from Adobe Exchange

### ISSUE THREAD

**Issue by pdophoto** [adobe-dmeservices/custom-metadata#8]
**Description**
Installation from Adobe Exchange failed repetivlly.

**Steps to reproduce**
Try it

**Workarounds**
None

**Expected behavior**
Adobe should check 

**Screenshots**
Impossible to get one, the download simply start and stop instantly.

**XMP Metadata**
Attach raw XMP metadata (if applicable). NA

**Metadata View JSON**
Export and attach your Metadata View JSON (if applicable). NA

**Environment**
* OS type and version: Windows 10 up to date
* Extension version: Last
* Any other relevant info:

**Comment by jameslockman** [comment]
Until recently, installing from Exchange is not supported for Enterprise customers. We have introduced options in the Packager to allow Packaging Admins to include specific extensions in their Creative Cloud packages. See [https://helpx.adobe.com/enterprise/admin-guide.html/enterprise/using/manage-extensions.ug.html](https://helpx.adobe.com/enterprise/admin-guide.html/enterprise/using/manage-extensions.ug.html)

If you are unable to use the Enterprise Packaging tools, then please download the extension from the [Releases tab in this github](https://github.com/adobe-dmeservices/custom-metadata/releases) and install using [Anastasiy's Extension Manager](https://install.anastasiy.com).
