### ISSUE TITLE
Text fields with very long values are hard to read/edit

### ISSUE THREAD

**Issue by MetadataDeluxe** [adobe-dmeservices/custom-metadata#9]
Some fields, i.e., Description/Caption, commonly contain very long strings (paragraphs). These are hard to read and edit in the current UI text box which displays a single line of truncated text. I can use the left/right arrow keys to see the text, but I loose context of the sentence/paragraph, which makes it difficult to edit.

When I click on a text box, I would like either:
1. The text box height expands so that all of the text is visible until I click on another UI element, then it returns to a single row height).
2. The text box becomes a scrollable text area, about 3 times it's normal height (so 3 lines are visible) until I click on another UI element, then it returns to a single row height).

My alternative solution to the current UI is to copy and paste a long caption it into a text editor, make my edits, then paste it back into the metadata panel text box.

Example Description/Caption (screen shot of current UI display attached):
" Daniel Chester French (American sculptor, 1850-1931); Abraham Lincoln; General view of statue and inscription behind it; 1914-1920 (creation); pedestal and platform for statue: Tennessee marble; statue: white Georgia marble; 5.79 m (height, statue); Lincoln Memorial (Washington, District of Columbia, United States); part of: Lincoln Memorial"

![desc_single_line](https://user-images.githubusercontent.com/5862936/99486592-52806700-2919-11eb-93f4-2d1a2f19d890.png)

**Comment by jameslockman** [comment]
Would a third alternative work:
1. Text box has drag handles in the corner which lets the user resize the text box

We will consider these three approaches and add one to the roadmap.

**Comment by MetadataDeluxe** [comment]
That would also work if the text box maintains it's new size as new thumbnails are selected. Having to resize the text box every time would slow down workflow.

Thanks for considering this enhancement.

By the way, there are some really nice UI elements, such as the move up,  move down, delete buttons in the multi text list.
![multi_text_buttons](https://user-images.githubusercontent.com/5862936/99562171-a2dce080-297c-11eb-86d8-a157bd1aa5fa.png)

**Comment by MetadataDeluxe** [comment]
For reference, the default Bridge metadata panel automatically expands to display all the text in a field. This solution requires the fewest additional actions by the user - you just always see the full text.
![br_large_text_box](https://user-images.githubusercontent.com/5862936/99568199-fb63ac00-2983-11eb-9af9-a8c05fde9dad.png)

**Comment by jameslockman** [comment]
In the 1.3.0 release, we provided a method in the Configurator to indicate that a field is a multi-line text field. 
![image](https://user-images.githubusercontent.com/2659225/107521959-2889ba00-6b81-11eb-9cce-4d75d3cc91fd.png)

This option will expand the field and it will automatically grow to accommodate more text, based on its content.
![image](https://user-images.githubusercontent.com/2659225/107522247-7f8f8f00-6b81-11eb-9321-6b0bf93c5fdf.png)
